### PR TITLE
[WIP] Misc Cleanup of Chef Bot

### PR DESCRIPTION
**Pull request by EdHurtig**

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
This needs a strong review. Perhaps we hold off until other things are sorted?

**Comment by EdHurtig** [comment]
indeed

**Comment by EdHurtig** [comment]
It is still a WIP so no rush on this, was more of a "got upset that my code was so bad" moment

**Comment by EdHurtig** [comment]
Re-queueing this to review & merge in the next month

**Comment by EdHurtig** [comment]
@jeffbyrnes I would love to make this into a proper gem with gemspec, rspec, ect at some point. Do we have any good examples of a simple ruby script that is fully built out with all the bells and whistles?

**Comment by jeffbyrnes** [comment]
@EdHurtig sure do. Check out [cronitor](https://github.com/evertrue/cronitor). @eherot probably has some better suggestions, as well.

**Comment by jeffbyrnes** [comment]
@eherot not sure we’ll ever get around to this, but if we can, we should carry forward @EdHurtig’s improvements here. I wager there’s good stuff to sift out of all these changes.

**Comment by eherot** [comment]
IMO this should be made into a proper, full-fledged Gem.

**Comment by jeffbyrnes** [comment]
Yep, I’d agree, and @EdHurtig thought that, too.

**Comment by EdHurtig** [comment]
@jeffbyrnes @eherot https://media4.giphy.com/media/2IlIVI0ljtrZC/200_s.gif

**Comment by jeffbyrnes** [comment]
@haizhou not sure if y’all still use this at all, but this can definitely simply be closed out at this point, and maybe this repo archived if you don't use it anymore.

**Comment by EdHurtig** [comment]
Closing

**Pull request closed without merging**
